Repository unb-mds/2024-2-Squad06, pull requests merged in 2025-01, with the labels that each got.

#62 integração para tailwind e responsividade carrossel
  client/src/components/carrossel/carrosel.tsx
  client/src/components/carrossel/carroselStyle.css
Labels: Feature

#63 integração de Home e CardGastos para tailwind e responsividade
  client/src/components/CardGastos/CardGastos.tsx
  client/src/pages/Home/Home.tsx
  client/tailwind.config.js
Labels: Feature

#64 integração da BarraPesquisa para tailwind e responsividade
  client/src/components/home/BarraPesquisa/BarraPesquisa.tsx
  client/tailwind.config.js
Labels: Feature

#60 integração do footer para tailwind e responsividade
  client/src/components/Footer/Footer.tsx
Labels: Feature

#85 Feat(#84)/pagina monitoramento
  client/public/assets/BandAlagoas.png
  client/src/App.tsx
  client/src/components/CardGastos/CardGastos.tsx
  client/src/components/carrossel/carrosel.tsx
  client/src/components/home/BarraFiltragem/BarraFiltragem.tsx
  client/src/components/home/BarraPesquisa/BarraPesquisa.tsx
  client/src/pages/Filtragem/Filtragem.tsx
  client/src/pages/Monitoramento/Moitoramento.tsx
  client/src/pages/SobreProjeto/SobreProjeto.tsx
Labels: bug, Feature

#88 fix(#87)/Corrigindo docker-compose
  README.md
  docker-compose.yml
  manage.py
  server/README.md
Labels: Feature

#97 Dockerização do Frontend do projeto
  .dockerignore
  README.md
  client/Dockerfile
  client/nginx/nginx.conf
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  docker-compose.yml
Labels: documentação, Feature
